/*
 *
 * WalletPage constants
 *
 */

export const GENERATE_ACCOUNT_PRIMARY = 'app/WalletPage/GENERATE_ACCOUNT_PRIMARY';
export const GENERATE_ACCOUNT_SECONDARY = 'app/WalletPage/GENERATE_ACCOUNT_SECONDARY';
export const GENERATE_ACCOUNT_PRIMARY_SUCCESS = 'app/WalletPage/GENERATE_ACCOUNT_PRIMARY_SUCCESS';
export const GENERATE_ACCOUNT_SECONDARY_SUCCESS = 'app/WalletPage/GENERATE_ACCOUNT_SECONDARY_SUCCESS';
export const GENERATE_ACCOUNT_ERROR = 'app/WalletPage/GENERATE_ACCOUNT_ERROR';

export const RESTORE_ACCOUNT_PRIMARY = 'app/WalletPage/RESTORE_ACCOUNT_PRIMARY';
export const RESTORE_ACCOUNT_SECONDARY = 'app/WalletPage/RESTORE_ACCOUNT_SECONDARY';

export const SEND_TRANSACTION = 'app/WalletPage/SEND_TRANSACTION';
export const SEND_TRANSACTION_SUCCESS = 'app/WalletPage/SEND_TRANSACTION_SUCCESS';
export const SEND_TRANSACTION_ERROR = 'app/WalletPage/SEND_TRANSACTION_ERROR';

export const CHANGE_ADDRESS = 'app/WalletPage/CHANGE_ADDRESS';
export const CHANGE_AMOUNT = 'app/WalletPage/CHANGE_AMOUNT';

export const GET_FAUCET_BALANCE = 'app/WalletPage/GET_FAUCET_BALANCE';
export const GET_FAUCET_BALANCE_SUCCESS = 'app/WalletPage/GET_FAUCET_BALANCE_SUCCESS';
export const GET_FAUCET_BALANCE_ERROR = 'app/WalletPage/GET_FAUCET_BALANCE_ERROR';

export const TOGGLE_SELECTED_ACCOUNT = 'app/WalletPage/TOGGLE_SELECTED_ACCOUNT';

export const CHANGE_NETWORK = 'app/WalletPage/CHANGE_NETWORK';
export const SELECT_ACCOUNT = 'app/WalletPage/SELECT_ACCOUNT';

export const ADD_ACCOUNT = 'app/WalletPage/ADD_ACCOUNT';
export const ADD_ACCOUNT_SUCCESS = 'app/WalletPage/ADD_ACCOUNT_SUCCESS';
export const ADD_ACCOUNT_ERROR = 'app/WalletPage/ADD_ACCOUNT_ERROR';

export const TOGGLE_DROPDOWN = 'app/WalletPage/TOGGLE_DROPDOWN';
export const SELECT_PAGE = 'app/WalletPage/SELECT_PAGE';

export const RECAPTCHA_CHANGE = 'app/WalletPage/RECAPTCHA_CHANGE';

export const MNEMONIC_REGENERATE = 'app/WalletPage/MNEMONIC_REGENERATE';
export const MNEMONIC_REGENERATE_SUCCESS = 'app/WalletPage/MNEMONIC_REGENERATE_SUCCESS';

